config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
metadata:
  site_url: 'https://nimble-torte-5e9a05.netlify.app/'
  site_title: Xavi
  site_subtitle_1: Works
  site_subtitle_2: 'Quito, EC'
  site_description: |
    I'm an artist and designer whose work is rooted in the beauty of nature and driven by a desire to express what lies beyond words.
  site_email: xavierplasso@gmail.com
  site_social_url: 'https://instagram.com/xavipl__'
  site_icon_svg: /assets/uploads/android-chrome-192x192.png
  site_icon_png: ''
  site_ga4_id: ''
  seo:
    site_title: Xavi Works
    site_description: 'A Digital Garden by Xavi.'
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FFFFFF'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: false
images:
  avif:
    enabled: false
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: Instagram
